// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhAR2hi_za-MZm15Y8jaynYH9PjgiiXK0',
    appId: '1:936845927498:web:cc774df2c63809799c32b3',
    messagingSenderId: '936845927498',
    projectId: 'heepmee-7ade2',
    authDomain: 'heepmee-7ade2.firebaseapp.com',
    storageBucket: 'heepmee-7ade2.appspot.com',
    measurementId: 'G-5YQ99JKCWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzF0hirR0OYASwaWtE7lNETk40nMpnqUY',
    appId: '1:936845927498:android:a3ed51cc5b6bb06c9c32b3',
    messagingSenderId: '936845927498',
    projectId: 'heepmee-7ade2',
    storageBucket: 'heepmee-7ade2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_altKjMjmegNsTXgCaOqmkxeC9d0y3Co',
    appId: '1:936845927498:ios:2803b9fbad38015e9c32b3',
    messagingSenderId: '936845927498',
    projectId: 'heepmee-7ade2',
    storageBucket: 'heepmee-7ade2.appspot.com',
    iosBundleId: 'com.example.heepme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_altKjMjmegNsTXgCaOqmkxeC9d0y3Co',
    appId: '1:936845927498:ios:2803b9fbad38015e9c32b3',
    messagingSenderId: '936845927498',
    projectId: 'heepmee-7ade2',
    storageBucket: 'heepmee-7ade2.appspot.com',
    iosBundleId: 'com.example.heepme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhAR2hi_za-MZm15Y8jaynYH9PjgiiXK0',
    appId: '1:936845927498:web:151251f245ff6f979c32b3',
    messagingSenderId: '936845927498',
    projectId: 'heepmee-7ade2',
    authDomain: 'heepmee-7ade2.firebaseapp.com',
    storageBucket: 'heepmee-7ade2.appspot.com',
    measurementId: 'G-Q5JQY0S8S4',
  );
}
